---
title: "Advent Of Code"
author: "Issa Sanogo"
date: '`r format(Sys.Date(), "%d/%m/%Y")`'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(stringsAsFactors = FALSE)

# Packages
library(tidyverse)
```

```{r function}
# !is.na
not_na <- Negate(is.na)
# !%in%
`%not_in%` <- Negate(`%in%`)
```


# AOC 2020

## --- Day 1 : Report Repair ---

```{r day1-input}
# read the input
input <- readLines("./data/2020/day1-input.txt")
```

### Part One

```{r part one}
two_entrie <- combn(input, 2) %>% # create a matrix of possible
  as_tibble() %>%
  map_df(as.numeric)
two_entrie <- unlist(two_entrie[colSums(two_entrie) == 2020], use.names = FALSE)
two_entrie
sum(two_entrie)
as.character(prod(two_entrie))
```

### Part Two

```{r part two}
three_entrie <- combn(input, 3) %>%
  as_tibble() %>%
  map_df(as.numeric)
three_entrie <- unlist(three_entrie[colSums(three_entrie) == 2020], use.names = FALSE)
three_entrie
sum(three_entrie)
as.character(prod(three_entrie))
```

## --- Day 2: Password Philosophy ---

```{r day2-input}
# read the input
input <- readLines("./data/2020/day2-input.txt")
```

```{r part one}
valid_passwd <- str_split(input, pattern = ":\\s", simplify = TRUE) %>% 
  as_tibble() %>% 
  set_names(c("policy", "passwd")) %>% 
  separate(policy, into = c("min", "max"), sep = "-") %>% 
  separate(max, into = c("max", "letter"), sep = "\\s") %>% 
  mutate(N = str_count(passwd, pattern = letter),
         min = as.numeric(min),
         max = as.numeric(max))
sum(valid_passwd$N >= valid_passwd$min & valid_passwd$N <= valid_passwd$max)
```

```{r part two}
res <- valid_passwd %>%
  mutate(pos1 = str_sub(passwd, min, min),
         pos2 = str_sub(passwd, max, max),
         pos1_verif = pos1 == letter,
         pos2_verif = pos2 == letter,
         verif = pos1_verif + pos2_verif) %>%
  filter(verif == 1) %>% 
  nrow()
```

## --- Day 3: Toboggan Trajetory ---

```{r day3-input}
# read the input
input <- readLines("./data/2020/day3-input.txt")
trajet <- str_split(input, pattern = "")

# Function to traverse the forest
traverse <- function (right, down) {
  trajet <- trajet[seq(1, length(input), down)]
  pos <- cumsum(rep(right, times = length(trajet) - 1 )) + 1
  pos <- c(1, pos)
  while (any(pos > 31))  pos[pos > 31] <- pos[pos > 31] - 31
  res <- sapply(seq_along(pos), function(x) trajet[[x]][pos[x]])
  sum(res == "#") 
}
```

```{r part one}
traverse(3, 1)
```

```{r part one}
traverse(1, 1) * traverse(3, 1) * traverse(5, 1) * traverse(7, 1) * traverse(1, 2)
```

## --- Day 4: Passport Processing ---

```{r day4-input}
# read the input
input <- readLines("./data/2020/day4-input.txt")
passport <- input %>%
  str_c(collapse = "\n") %>%
  str_split(pattern = "\n\n") %>%
  unlist() %>%
  as_tibble()
```

```{r part one}
passport %>% 
  mutate(byr = str_detect(value, pattern = "byr"),
         iyr = str_detect(value, pattern = "iyr"),
         eyr = str_detect(value, pattern = "eyr"),
         hgt = str_detect(value, pattern = "hgt"),
         hcl = str_detect(value, pattern = "hcl"),
         ecl = str_detect(value, pattern = "ecl"),
         pid = str_detect(value, pattern = "pid")
  ) %>%
  filter(byr, iyr, eyr, hgt, hcl, ecl, pid) %>% 
  nrow()
```

```{r part two}
passport %>% 
  mutate(value = str_replace(value, pattern = "\\s+", replacement = " "),
         byr = as.numeric(str_extract(value, pattern = "(?<=byr:)(\\d+)")),
         iyr = as.numeric(str_extract(value, pattern = "(?<=iyr:)(\\d+)")),
         eyr = as.numeric(str_extract(value, pattern = "(?<=eyr:)(\\d+)")),
         hgt = str_extract(value, pattern = "(?<=hgt:)(\\d+[[:alpha:]]+)"),
         hgt_unit = str_extract(hgt, pattern = "[[:alpha:]]+"),
         hgt = as.numeric(str_extract(hgt, pattern = "\\d+")),
         hcl = str_extract(value, pattern = "(?<=hcl:)(#[0-9a-f]+)"),
         ecl = str_extract(value, pattern = "(?<=ecl:)([[:alpha:]]+)"),
         pid = str_extract(value, pattern = "(?<=pid:)\\d+")
  ) %>%
  filter(byr >= 1920 & byr <= 2002 &
           iyr >= 2010 & iyr <= 2020 &
           eyr >= 2020 & eyr <= 2030 &
           ((hgt >= 150 & hgt <= 193 & hgt_unit == "cm")|(hgt >= 59 & hgt <= 76 & hgt_unit == "in")) &
           nchar(hcl) == 7 &
           str_detect(ecl, pattern = "amb$|blu$|brn$|gry$|grn$|hzl$|oth$") &
           nchar(pid) == 9
  ) %>% 
  nrow()
```

## --- Day 5: Binary Boarding ---

```{r}

```

